CREATE TABLE if NOT EXISTS `cm78542_mpacms`.`t_s_iblockType`
(
	ID INT(18) NOT NULL auto_increment,
	DATE_INSERT datetime NOT NULL,
	DATE_UPDATE datetime NOT NULL,
	TITLE VARCHAR(255),
	CODE VARCHAR(255),
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID)
);

CREATE TABLE if NOT EXISTS `cm78542_mpacms`.`t_s_iblock`
(
	ID INT(18) NOT NULL auto_increment,
	IBLOCK_TYPE_ID INT(18) NOT NULL,
	DATE_INSERT datetime NOT NULL,
	DATE_UPDATE datetime NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	CODE VARCHAR(255) NOT NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID)
);

CREATE TABLE if NOT EXISTS `cm78542_mpacms`.`t_s_iblock_element`
(
	ID INT(18) NOT NULL auto_increment,
	IBLOCK_ID INT(18) NOT NULL,
	DATE_INSERT datetime NOT NULL,
	DATE_UPDATE datetime NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	CODE VARCHAR(255) NOT NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID)
);

CREATE TABLE if NOT EXISTS `cm78542_mpacms`.`t_s_iproperty`
(
	ID INT(18) NOT NULL auto_increment,
	IBLOCK_ID INT(18) NOT NULL,
	DATE_INSERT datetime NOT NULL,
	DATE_UPDATE datetime NOT NULL,
	NAME VARCHAR(255),
	CODE VARCHAR(255),
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	MULTY CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID)
);

CREATE TABLE if NOT EXISTS `cm78542_mpacms`.`t_s_iproperty_value`
(
	ID INT(18) NOT NULL auto_increment,
	IPROPERTY_ID INT(18) NOT NULL,
	IBLOCK_ELEMENT_ID INT(18) NOT NULL,
	DATE_INSERT datetime NOT NULL,
	DATE_UPDATE datetime NOT NULL,
	VALUE LONGTEXT NOT NULL,
	PRIMARY KEY (ID)
);